[package]
name = "sprinkle"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.2.0"
byte-unit = "4.0.13"
colored = "1.6.1"
rsass = "0.23.0"
term-table = "1.3.2"